name: flutter_advanced
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Splashing
  flutter_native_splash: ^2.3.5
  # Localization
  intl: ^0.18.0
  easy_localization: ^3.0.3
  # State management.
  flutter_bloc: ^8.1.3
  # Code generation for immutable classes (cubit & retrofit).
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  # Dependency injection.
  get_it: ^7.6.4
  # Classes and helper functions that support JSON code generation.
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  pretty_dio_logger: ^1.3.1
  # UI
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
